import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Index.module.css";
import Logo from "../public/logo.png";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { WilderForm } from "../components/WilderForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wilder Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <main className={styles.main}>
          <WilderForm />
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Home;
