import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Index.module.css";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { WilderForm } from "../components/WilderForm";
import { WildersList } from "../components/WildersList";
import { IWilder } from "../types/wilder";

const Home: NextPage = () => {
  const [wilders, setWilders] = useState<IWilder[]>([]);
  return (
    <>
      <Head>
        <title>Wilder Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <WilderForm wilders={wilders} setWilders={setWilders} />
        <WildersList wilders={wilders} setWilders={setWilders} />
        <Footer />
      </div>
    </>
  );
};

export default Home;
